<!-- BEGIN: RECENTCOMMENTS -->
<div id='{RECENTCOMMENTS_AJAX_OPENDIVID}'>
<!-- BEGIN: COMM_ROW -->
	{RECENTCOMMENTS_ROW_DATE} <a href="{RECENTCOMMENTS_ROW_HREF}">{RECENTCOMMENTS_ROW_ITEM_TITLE}</a><br />
<!-- END: COMM_ROW -->
	{RECENTCOMMENTS_WARNINGS}
	<div class="pagnav">{RECENTCOMMENTS_PAGINATION_PREV} {RECENTCOMMENTS_PAGNAV} {RECENTCOMMENTS_PAGINATION_NEXT}</div>
</div>
<!-- END: RECENTCOMMENTS-->
